FROM ubuntu:trusty
MAINTAINER Stefan Berggren <nsg@nsg.cc>

# Make sure we are up-to-date
RUN apt-get -y update && apt-get -y upgrade

# Install packages needed to build the binary
RUN apt-get -y install git wget zip unzip \
	build-essential cmake libglew-dev \
	xorg-dev python-pip binutils-mingw-w64-i686 \
	gcc-mingw-w64-i686 g++-mingw-w64-i686  \
	&& apt-get -y build-dep glfw

# Setup build dir
RUN mkdir /build
WORKDIR /build
