FROM fedora:23
MAINTAINER Stefan Berggren <nsg@nsg.cc>

RUN yum -y groupinstall "Development Tools"
RUN yum -y update && yum -y upgrade
RUN yum -y install git wget zip unzip cmake \
	glew-devel mingw64-binutils mingw64-gcc \
	mingw64-gcc-c++ mingw32-binutils \
	mingw32-gcc mingw32-gcc-c++ \
	libXinerama-devel libXcursor-devel \
	zlib-devel xorg-x11-server-devel \
	mesa-libGL-devel libXrandr-devel

# Setup build dir
RUN mkdir /build
WORKDIR /build
